sudo:
  false

language:
  php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

cache:
  directories:
    - vendor

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=PSR2 src/
  - vendor/bin/phpmd src/ text cleancode,codesize,controversial,design,naming,unusedcode
  - vendor/bin/phpunit --colors --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

matrix:
  allow_failures:
    - php: hhvm-nightly

notifications:
  email: false
